name = "piragh-website"
compatibility_date = "2024-01-15"

# For Cloudflare Pages deployment
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Environment variables
[vars]
NODE_ENV = "production"

# Pages configuration
[pages]
build = { command = "npm run build" }
output_directory = "dist"
